<h2 id="numpy"> D1 What is Numpy?</h2>


NumPy is a Python library used for working with arrays, linear algebra, fourier transform, and matrices.A numpy array is similar to a list. NumPy stands for Numerical Python and it is an open source project.The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

NumPy is usually imported under the np alias.

It's usually fixed in size and each element is of the same type. We can cast a list to a numpy array by first importing `numpy`:


In [1]:
# import numpy library

import numpy as np 

In [2]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [3]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [5]:
# Check the Numpy version
print(np.__version__)

1.21.5


In [6]:
# Check the type of the array

type(a)

numpy.ndarray

In [7]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int64')

Check the type of the array and Value type for the given array **c**


In [10]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

type(b)


numpy.ndarray

In [11]:
b.dtype

dtype('float64')

<h3 id="val">Assign value</h3>


In [13]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

We can change the first element of the array to 100 as follows:


In [14]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [15]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

Assign the value 20 for the second element in the given array.


In [16]:
c[1] = 20
c

array([100,  20,   2,   3,   0])

<h3 id="slice">Slicing</h3>


Like lists, we can slice the numpy array. Slicing in python means taking the elements from the given index to another given index.

We pass slice like this: [start:end].The element at end index is not being included in the output.

We can select the elements from 1 to 3 and assign it to a new numpy array <code>d</code> as follows:


In [17]:
# Slicing the numpy array

d = c[1:4]
d

array([20,  2,  3])

In [18]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,  20,   2, 300, 400])

We can also define the steps in slicing, like this: [start:end:step].


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


If we don't pass start its considered 0


In [21]:
print(arr[:4])

[1 2 3 4]


If we don't pass end it considers till the length of array.


In [22]:
print(arr[4:])

[5 6 7]


If we don't pass step its considered 1


In [23]:
print(arr[1:5:])

[2 3 4 5]


Print the even elements in the given array.


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[1:8:2])

[2 4 6 8]


Similarly, we can use a list to select more than one specific index.
The list `select` contains several values:


In [27]:
# Create the index list

select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

We can use the list as an argument in the brackets. The output is the elements corresponding to the particular indexes:


In [28]:
# Use List to select elements

d = c[select]
d

array([100,   2, 300, 400])

In [29]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,     20, 100000, 100000, 100000])

In [30]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [31]:
# Get the size of numpy array

a.size

5

In [32]:
a.ndim

1

In [33]:
a.shape

(5,)

In [35]:

X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y
Z

array([[1, 1],
       [1, 1]])

In [36]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0,1:3]
out

array([0, 1])

In [38]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])

In [58]:
a=np.array([0,1,0,1,0]) 
b=np.array([1,0,1,0,1]) 
a+b

array([1, 1, 1, 1, 1])

In [59]:
a=np.array([1,1,1,1,1]) 
a+10

array([11, 11, 11, 11, 11])

### Numpy Statistical Functions


In [60]:
# Create a numpy array

a = np.array([1, -1, 1, -1])

In [61]:
# Get the mean of numpy array

mean = a.mean()
mean

0.0

In [62]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

1.0

In [63]:
# Create a numpy array

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [64]:
# Get the biggest value in the numpy array

max_b = b.max()
max_b

5

In [65]:
# Get the smallest value in the numpy array

min_b = b.min()
min_b

-1

Find the sum of maximum and minimum value in the given numpy array


In [68]:
c = np.array([-10, 201, 43, 94, 502])

sum_min_max = c.max() + c.min()
sum_min_max

492